mv RSGraviton600/*/*/*/*/ReducedSelection_* RSGraviton600/
mv RSGraviton800/*/*/*/*/ReducedSelection_* RSGraviton800/
mv RSGraviton1000/*/*/*/*/ReducedSelection_* RSGraviton1000/
mv RSGraviton1200/*/*/*/*/ReducedSelection_* RSGraviton1200/
mv RSGraviton1400/*/*/*/*/ReducedSelection_* RSGraviton1400/
mv RSGraviton1600/*/*/*/*/ReducedSelection_* RSGraviton1600/
mv RSGraviton1800/*/*/*/*/ReducedSelection_* RSGraviton1800/
mv RSGraviton2000/*/*/*/*/ReducedSelection_* RSGraviton2000/
mv RSGraviton2500/*/*/*/*/ReducedSelection_* RSGraviton2500/
mv RSGraviton3000/*/*/*/*/ReducedSelection_* RSGraviton3000/
mv RSGraviton3500/*/*/*/*/ReducedSelection_* RSGraviton3500/
mv RSGraviton4000/*/*/*/*/ReducedSelection_* RSGraviton4000/
mv RSGraviton4500/*/*/*/*/ReducedSelection_* RSGraviton4500/
mv BulkGraviton800/*/*/*/*/ReducedSelection_* BulkGraviton800/
mv BulkGraviton1000/*/*/*/*/ReducedSelection_* BulkGraviton1000/
mv BulkGraviton1200/*/*/*/*/ReducedSelection_* BulkGraviton1200/
mv BulkGraviton1400/*/*/*/*/ReducedSelection_* BulkGraviton1400/
mv BulkGraviton1600/*/*/*/*/ReducedSelection_* BulkGraviton1600/
mv BulkGraviton1800/*/*/*/*/ReducedSelection_* BulkGraviton1800/
mv BulkGraviton2000/*/*/*/*/ReducedSelection_* BulkGraviton2000/
mv BulkGraviton2500/*/*/*/*/ReducedSelection_* BulkGraviton2500/
mv BulkGraviton3000/*/*/*/*/ReducedSelection_* BulkGraviton3000/
mv BulkGraviton3500/*/*/*/*/ReducedSelection_* BulkGraviton3500/
mv BulkGraviton4000/*/*/*/*/ReducedSelection_* BulkGraviton4000/
mv BulkGraviton4500/*/*/*/*/ReducedSelection_* BulkGraviton4500/
mv WJets/*/*/*/*/ReducedSelection_* WJets/
mv WJets100/*/*/*/*/ReducedSelection_* WJets100/
mv WJets200/*/*/*/*/ReducedSelection_* WJets200/
mv WJets400/*/*/*/*/ReducedSelection_* WJets400/
mv WJets600/*/*/*/*/ReducedSelection_* WJets600/
mv TTbar/*/*/*/*/ReducedSelection_* TTbar/
mv TTbar_amcatnlo/*/*/*/*/ReducedSelection_* TTbar_amcatnlo/
mv TTbar_powheg/*/*/*/*/ReducedSelection_* TTbar_powheg/
mv TTbar_madgraph/*/*/*/*/ReducedSelection_* TTbar_madgraph/
mv WW/*/*/*/*/ReducedSelection_* WW/
mv WZ/*/*/*/*/ReducedSelection_* WZ/
mv ZZ/*/*/*/*/ReducedSelection_* ZZ/
mv WW_excl/*/*/*/*/ReducedSelection_* WW_excl/
mv WZ_excl/*/*/*/*/ReducedSelection_* WZ_excl/
mv ZZ_excl/*/*/*/*/ReducedSelection_* ZZ_excl/
mv sch/*/*/*/*/ReducedSelection_* sch/
mv sch_bar/*/*/*/*/ReducedSelection_* sch_bar/
mv tch/*/*/*/*/ReducedSelection_* tch/
mv tch_bar/*/*/*/*/ReducedSelection_* tch_bar/
mv tWch/*/*/*/*/ReducedSelection_* tWch/
mv tWch_bar/*/*/*/*/ReducedSelection_* tWch_bar/
mv WJets_50ns/*/*/*/*/ReducedSelection_* WJets_50ns/
mv TTbar_amcatnlo_50ns/*/*/*/*/ReducedSelection_* TTbar_amcatnlo_50ns/
mv TTbar_powheg_50ns/*/*/*/*/ReducedSelection_* TTbar_powheg_50ns/
mv TTbar_madgraph_50ns/*/*/*/*/ReducedSelection_* TTbar_madgraph_50ns/
mv WW_50ns/*/*/*/*/ReducedSelection_* WW_50ns/
mv WZ_50ns/*/*/*/*/ReducedSelection_* WZ_50ns/
mv ZZ_50ns/*/*/*/*/ReducedSelection_* ZZ_50ns/
mv tch_50ns/*/*/*/*/ReducedSelection_* tch_50ns/
mv tch_bar_50ns/*/*/*/*/ReducedSelection_* tch_bar_50ns/
mv tWch_50ns/*/*/*/*/ReducedSelection_* tWch_50ns/
mv tWch_bar_50ns/*/*/*/*/ReducedSelection_* tWch_bar_50ns/
mv data_mu/*/*/*/*/ReducedSelection_* data_mu/
mv data_el/*/*/*/*/ReducedSelection_* data_el/
