import FWCore.ParameterSet.Config as cms

jetpropertiesPuppiAK8 = cms.EDProducer('JetPropertiesPuppiAK8',
JetTag_               = cms.InputTag('slimmedJetsPuppiAK8'),
prunedJetTag_               = cms.InputTag('slimmedJetsPuppiAK8'),
softdropJetTag_               = cms.InputTag('slimmedJetsPuppiAK8'),
MinPt = cms.double(15),
#puppiJetTag_               = cms.InputTag('ak10PFJetsPuppiAK8'),
doJEC = cms.bool(False),
doReclusteringForPrunedAndSoftdrop = cms.bool(False),
RhoTag = cms.InputTag("fixedGridRhoFastjetAll"),
BTagInputTag	        = cms.string('combinedSecondaryVertexBJetTags'),
L1File = cms.string("Spring16_25nsV3_DATA_L1FastJet_AK8PFPuppi.txt"),
L2File = cms.string("Spring16_25nsV3_DATA_L2Relative_AK8PFPuppi.txt"),
L3File = cms.string("Spring16_25nsV3_DATA_L3Absolute_AK8PFPuppi.txt"),
L2L3File = cms.string("Spring16_25nsV3_DATA_L2L3Residual_AK8PFPuppi.txt"),
uncFile = cms.string("Spring16_25nsV3_DATA_Uncertainty_AK8PFPuppi.txt"),
#L1File = cms.string("PHYS14_25_V2_All_L1FastJet_AK8PFchs.txt"),
#L2File = cms.string("PHYS14_25_V2_All_L2Relative_AK8PFchs.txt"),
#L3File = cms.string("PHYS14_25_V2_All_L3Absolute_AK8PFchs.txt"),
#jecPayloadNames      = cms.vstring("JEC/PHYS14_25_V2::All_L3Absolute_AK8PFchs.txt","JEC/PHYS14_25_V2::All_L2Relative_AK8PFchs.txt","JEC/PHYS14_25_V2::All_L1FastJet_AK8PFchs.txt"),
)
