import FWCore.ParameterSet.Config as cms

jetpropertiesAK12 = cms.EDProducer('JetPropertiesAK12',
JetTag_               = cms.InputTag('slimmedJetsAK12'),
prunedJetTag_               = cms.InputTag('slimmedJetsAK12'),
softdropJetTag_               = cms.InputTag('slimmedJetsAK12'),
MinPt = cms.double(15),
#puppiJetTag_               = cms.InputTag('ak10PFJetsPuppi'),
doJEC = cms.bool(False),
doReclusteringForPrunedAndSoftdrop = cms.bool(False),
RhoTag = cms.InputTag("fixedGridRhoFastjetAll"),
BTagInputTag	        = cms.string('combinedSecondaryVertexBJetTags'),
L1File = cms.string("Summer15_25nsV6_DATA_L1FastJet_AK8PFchs.txt"),
L2File = cms.string("Summer15_25nsV6_DATA_L2Relative_AK8PFchs.txt"),
L3File = cms.string("Summer15_25nsV6_DATA_L3Absolute_AK8PFchs.txt"),
L2L3File = cms.string("Summer15_25nsV6_DATA_L2L3Residual_AK8PFchs.txt"),
uncFile = cms.string("Summer15_25nsV6_DATA_Uncertainty_AK8PFchs.txt"),
#L1File = cms.string("PHYS14_25_V2_All_L1FastJet_AK8PFchs.txt"),
#L2File = cms.string("PHYS14_25_V2_All_L2Relative_AK8PFchs.txt"),
#L3File = cms.string("PHYS14_25_V2_All_L3Absolute_AK8PFchs.txt"),
#jecPayloadNames      = cms.vstring("JEC/PHYS14_25_V2::All_L3Absolute_AK8PFchs.txt","JEC/PHYS14_25_V2::All_L2Relative_AK8PFchs.txt","JEC/PHYS14_25_V2::All_L1FastJet_AK8PFchs.txt"),
)
